export const APP_CONFIG = {
  name: 'MCI — Mapa da Compra Imobiliária',
  shortName: 'MCI',
  productName: 'Mapa da Compra Imobiliária',
  brandOwner: 'Universidade EPSA',
  description:
    'Diagnóstico Imobiliário Inteligente para ajudar clientes a entenderem qual caminho combina melhor com sua renda, entrada disponível, urgência e momento financeiro.',
  whatsappNumber: '5521982134226',
};

export const STATUS_OPTIONS = [
  'Novo diagnóstico',
  'Aguardando qualificação',
  'Em contato',
  'Qualificado',
  'Encaminhado para especialista',
  'Em análise/simulação',
  'Proposta enviada',
  'Em negociação',
  'Venda realizada',
  'Nutrição',
  'Perdido',
  'Retorno futuro',
  'Sem resposta',
  'Dados incompletos',
  'Aguardando documentação',
  'Lead duplicado',
];

export const KANBAN_COLUMNS = [
  'Novo diagnóstico',
  'Aguardando qualificação',
  'Em contato',
  'Qualificado',
  'Encaminhado para especialista',
  'Em análise/simulação',
  'Proposta enviada',
  'Em negociação',
  'Venda realizada',
  'Nutrição',
  'Perdido',
];

export const ORIGENS = [
  'Tráfego pago',
  'Orgânico',
  'Parceiro imobiliária',
  'Parceiro construtora',
  'Corretor parceiro',
  'Indicação',
  'Campanha interna',
  'Universidade EPSA',
  'MCI — Mapa da Compra Imobiliária',
  'Manual',
  'Outro',
];

export const ESTADOS_BR = [
  'AC',
  'AL',
  'AP',
  'AM',
  'BA',
  'CE',
  'DF',
  'ES',
  'GO',
  'MA',
  'MT',
  'MS',
  'MG',
  'PA',
  'PB',
  'PR',
  'PE',
  'PI',
  'RJ',
  'RN',
  'RS',
  'RO',
  'RR',
  'SC',
  'SP',
  'SE',
  'TO',
];