import { ProfileResult } from '@/types';

export const PROFILES: ProfileResult[] = [
  {
    id: 'financiamento',
    nome: 'Financiamento Imediato',
    fraseIdentificacao: 'Seu diagnóstico indica compatibilidade inicial com uma análise de financiamento, especialmente se existe renda comprovável, entrada disponível e necessidade de comprar em curto prazo.',
    explicacao: 'Este perfil aparece quando o cliente demonstra urgência maior, possível capacidade de comprovação de renda, alguma entrada disponível e interesse em resolver a compra com mais velocidade. Isso não significa aprovação garantida; significa que vale analisar essa possibilidade com mais profundidade.',
    pontosFavoraveis: [
      'Você demonstra maior urgência para comprar',
      'Pode ter renda comprovável',
      'Pode ter entrada ou recurso disponível',
      'Talvez já tenha imóvel ou região definidos',
      'O financiamento pode ser analisado como caminho de velocidade',
    ],
    pontosAtencao: [
      'Financiamento envolve juros e custo total relevante',
      'A parcela precisa caber com segurança no orçamento',
      'É preciso analisar CET, prazo, seguros, entrada e custo total',
      'Aprovação depende da política do banco e da documentação',
      'Velocidade não deve substituir planejamento',
    ],
    proximoPasso: 'O próximo passo recomendado é realizar uma análise de viabilidade com base em renda, entrada, valor do imóvel, documentação e prazo desejado.',
    cta: 'Simular meu financiamento com orientação',
    ctaMensagem: 'Olá! Acabei de fazer o Diagnóstico de Compra Imobiliária Inteligente. Meu perfil foi: Financiamento Imediato. Quero entender, com calma, qual seria o próximo passo mais adequado para minha realidade.',
  },
  {
    id: 'consorcio',
    nome: 'Consórcio Planejado',
    fraseIdentificacao: 'Seu diagnóstico indica compatibilidade inicial com uma estratégia de consórcio planejado, especialmente se você valoriza planejamento, disciplina e menor exposição a juros bancários.',
    explicacao: 'Este perfil aparece quando o cliente não precisa necessariamente do imóvel de forma imediata, valoriza planejamento financeiro e demonstra interesse em evitar os juros tradicionais do financiamento. Consórcio precisa ser analisado com responsabilidade, sem promessa de contemplação rápida.',
    pontosFavoraveis: [
      'Você pode esperar um pouco mais',
      'Demonstra preocupação com juros',
      'Valoriza planejamento',
      'Pode ter disciplina mensal',
      'Pode se beneficiar de uma estratégia de crédito e lance',
    ],
    pontosAtencao: [
      'Consórcio não garante contemplação imediata',
      'É necessário entender sorteio, lance, prazo e grupo',
      'A parcela precisa ser sustentável ao longo do tempo',
      'A administradora precisa ser confiável',
      'O crédito deve estar alinhado ao valor real do imóvel desejado',
    ],
    proximoPasso: 'O próximo passo recomendado é montar uma estratégia de consórcio com valor de crédito, parcela, prazo, possibilidade de lance e objetivo de compra.',
    cta: 'Montar minha estratégia de consórcio',
    ctaMensagem: 'Olá! Acabei de fazer o Diagnóstico de Compra Imobiliária Inteligente. Meu perfil foi: Consórcio Planejado. Quero entender, com calma, qual seria o próximo passo mais adequado para minha realidade.',
  },
  {
    id: 'hibrida',
    nome: 'Estratégia Híbrida',
    fraseIdentificacao: 'Seu diagnóstico indica que talvez o melhor caminho não seja escolher apenas entre financiamento ou consórcio, mas comparar alternativas e combinar possibilidades.',
    explicacao: 'Este perfil aparece quando o cliente tem uma realidade intermediária: pode ter parte da entrada, alguma urgência e alguma capacidade de pagamento, mas ainda precisa organizar melhor a rota. Pode fazer sentido comparar entrada, FGTS, financiamento, consórcio e prazo.',
    pontosFavoraveis: [
      'Você pode ter parte da entrada, mas ainda precisar ajustar a estratégia',
      'Pode estar entre comprar agora e planejar melhor',
      'Pode se beneficiar de uma comparação entre alternativas',
      'Pode usar mais de uma estratégia',
      'Uma análise personalizada pode revelar caminhos mais seguros',
    ],
    pontosAtencao: [
      'Estratégia híbrida exige análise mais cuidadosa',
      'Pequenas diferenças de entrada, renda ou imóvel mudam o melhor caminho',
      'É preciso comparar custo, prazo, segurança e objetivo',
      'Não basta olhar apenas a parcela',
      'Pode ser necessário ajustar expectativa de imóvel ou prazo',
    ],
    proximoPasso: 'O próximo passo recomendado é comparar cenários para entender qual combinação faz mais sentido para sua renda, entrada, urgência e objetivo.',
    cta: 'Comparar meus caminhos possíveis',
    ctaMensagem: 'Olá! Acabei de fazer o Diagnóstico de Compra Imobiliária Inteligente. Meu perfil foi: Estratégia Híbrida. Quero entender, com calma, qual seria o próximo passo mais adequado para minha realidade.',
  },
  {
    id: 'reorganizacao',
    nome: 'Reorganização Financeira',
    fraseIdentificacao: 'Seu diagnóstico indica que talvez o melhor passo agora seja preparar melhor sua estrutura financeira antes de assumir um compromisso imobiliário.',
    explicacao: 'Este perfil aparece quando existem sinais de que o cliente deseja comprar, mas ainda pode não ter estrutura suficiente para avançar com segurança. Isso não significa desistir do imóvel; significa criar uma rota mais segura.',
    pontosFavoraveis: [
      'Você já começou a buscar clareza sobre sua compra',
      'Pode ser possível construir uma rota de preparação',
      'Organizar entrada, renda e dívidas melhora sua posição futura',
      'A preparação pode evitar pressão financeira depois',
      'Entender seu limite real aumenta a segurança da decisão',
    ],
    pontosAtencao: [
      'Comprar no momento errado pode gerar pressão financeira',
      'Parcela baixa não significa compra segura',
      'Sem organização, qualquer produto pode virar problema',
      'É preciso entender renda, dívidas, entrada e capacidade real',
      'A preparação pode ser mais importante que a velocidade',
    ],
    proximoPasso: 'O próximo passo recomendado é montar um plano de preparação com faixa de imóvel possível, meta de entrada, organização de dívidas e capacidade mensal segura.',
    cta: 'Criar meu plano de preparação para comprar',
    ctaMensagem: 'Olá! Acabei de fazer o Diagnóstico de Compra Imobiliária Inteligente. Meu perfil foi: Reorganização Financeira. Quero entender, com calma, qual seria o próximo passo mais adequado para minha realidade.',
  },
  {
    id: 'investidor',
    nome: 'Investidor Patrimonial',
    fraseIdentificacao: 'Seu diagnóstico indica uma visão mais patrimonial: o imóvel aparece não apenas como moradia, mas como parte de uma estratégia de construção ou proteção de patrimônio.',
    explicacao: 'Este perfil aparece quando o cliente demonstra visão de médio e longo prazo, interesse em patrimônio, valorização, diversificação ou renda futura. A decisão deve considerar custo do dinheiro, liquidez, prazo, risco e objetivo patrimonial.',
    pontosFavoraveis: [
      'Você pensa em patrimônio e longo prazo',
      'Pode comparar diferentes formas de aquisição',
      'Pode não depender do imóvel imediatamente',
      'Busca inteligência financeira, não apenas aprovação',
      'Pode se beneficiar de uma análise mais sofisticada',
    ],
    pontosAtencao: [
      'Nem todo imóvel é bom investimento',
      'Liquidez precisa ser considerada',
      'Valorização não é garantida',
      'Custo de oportunidade importa',
      'Estratégia patrimonial exige análise de risco e horizonte de tempo',
    ],
    proximoPasso: 'O próximo passo recomendado é montar uma análise patrimonial considerando objetivo, prazo, capital disponível, renda, risco, liquidez e tipo de imóvel desejado.',
    cta: 'Montar minha estratégia patrimonial',
    ctaMensagem: 'Olá! Acabei de fazer o Diagnóstico de Compra Imobiliária Inteligente. Meu perfil foi: Investidor Patrimonial. Quero entender, com calma, qual seria o próximo passo mais adequado para minha realidade.',
  },
  {
    id: 'emocional',
    nome: 'Compra Emocional de Risco',
    fraseIdentificacao: 'Seu diagnóstico indica um desejo forte de comprar, mas também alguns sinais de atenção que merecem ser avaliados antes de qualquer compromisso.',
    explicacao: 'Este perfil aparece quando existe urgência alta, pressão emocional, pouca clareza financeira, entrada insuficiente ou risco de tomar uma decisão apenas para resolver uma dor imediata. Não é um julgamento; é um alerta de proteção.',
    pontosFavoraveis: [
      'Você tem motivação real para conquistar o imóvel',
      'Está disposto a agir e buscar uma solução',
      'Com orientação, pode transformar urgência em plano',
      'O desejo de compra pode ser organizado com método',
      'Buscar análise antes de decidir já reduz risco',
    ],
    pontosAtencao: [
      'Urgência não substitui planejamento',
      'Parcela que cabe hoje pode apertar amanhã',
      'Promessas fáceis merecem cuidado',
      'Comprar sob pressão pode gerar arrependimento',
      'É importante comparar possibilidades antes de decidir',
    ],
    proximoPasso: 'O próximo passo recomendado é fazer uma análise segura antes de escolher financiamento, consórcio ou qualquer compromisso de compra.',
    cta: 'Fazer uma análise segura antes de decidir',
    ctaMensagem: 'Olá! Acabei de fazer o Diagnóstico de Compra Imobiliária Inteligente. Meu perfil foi: Compra Emocional de Risco. Quero entender, com calma, qual seria o próximo passo mais adequado para minha realidade.',
  },
];
